services:
  frontend_service:
    build:
      context: .
      dockerfile: services/frontend_service/Dockerfile
      cache_from:
        - sonny-frontend:latest
    image: sonny-frontend
    ports:
      # Override external port via FRONTEND_PORT env var; defaults to 8501
      - "${FRONTEND_PORT:-8501}:8501"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - OPENAI_API_KEY
      - BACKEND_CORE_URL=http://backend_core_service:8000
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
    networks:
      - sonny_net

  backend_core_service:
    build:
      context: services/backend_core_service
      cache_from:
        - sonny-backend-core:latest
    image: sonny-backend-core
    ports:
      # Override external port via BACKEND_PORT env var; defaults to 8000
      - "${BACKEND_PORT:-8000}:8000"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - OPENAI_API_KEY
      - SYMBOLIC_AI_URL=http://symbolic_ai_service:8001
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
    networks:
      - sonny_net

  symbolic_ai_service:
    build:
      context: services/symbolic_ai_service
      cache_from:
        - sonny-symbolic-ai:latest
    image: sonny-symbolic-ai
    ports:
      # Override external port via SYMBOLIC_PORT env var; defaults to 8001
      - "${SYMBOLIC_PORT:-8001}:8001"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - OPENAI_API_KEY
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 2
        delay: 10s
    networks:
      - sonny_net

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - sonny_net

  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - sonny_net

networks:
  sonny_net:
    driver: bridge